import { useEffect, useState, useCallback } from 'react';
import storage from '../lib/storage';

// mapping of friendly interval -> trading-day count
const INTERVAL_LOOKUP = {
  'Day': 1,
  'Week': 5,
  'Month': 22,
  'Year': 252
};

export default function useOHLCV() {
  const [coins, setCoins] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [snapshotCount, setSnapshotCount] = useState(0);
  const [latestTimestamp, setLatestTimestamp] = useState(null);

  const importSnapshotsIfNeeded = useCallback(async (force = false) => {
    try {
      const cnt = await storage.countSnapshots();
      if (!force && cnt && cnt > 0) {
        setSnapshotCount(cnt);
        return { imported: false, count: cnt };
      }
      setLoading(true);
      if (force && cnt && cnt > 0) {
        // clear DB to force a fresh import
        await storage.clearSnapshots();
      }
      // fetch prebuilt JSON (generated by scripts/generate_snapshots_json.cjs -> public/psx_snapshots.json)
      const res = await fetch('/psx_snapshots.json');
      if (!res.ok) throw new Error('Failed to fetch snapshots JSON');
      const list = await res.json();
      // If JSON is very large it likely contains full history; to avoid importing huge amounts
      // (and duplicate entries) collapse to latest-per-symbol when the file is enormous.
      let filteredList = list;
      if (Array.isArray(list) && list.length > 100000) {
        // keep only the latest timestamp record per symbol
        const latestBySymbol = new Map();
        for (const r of list) {
          const sym = r.symbol;
          const cur = latestBySymbol.get(sym);
          if (!cur || (r.ts || 0) > (cur.ts || 0)) latestBySymbol.set(sym, r);
        }
        filteredList = Array.from(latestBySymbol.values());
        console.info('[useOHLCV] large snapshots JSON detected; importing latest-per-symbol only', filteredList.length);
      } else {
        // remove exact duplicates (same symbol + ts) if any
        const seen = new Set();
        filteredList = list.filter((r) => {
          const k = `${r.symbol}|${r.ts}`;
          if (seen.has(k)) return false;
          seen.add(k);
          return true;
        });
        if (filteredList.length !== list.length) console.info('[useOHLCV] removed duplicate snapshot records', list.length - filteredList.length);
      }
      // convert to storage format
      const items = filteredList.map((r) => ({ symbol: r.symbol, market: r.market || 'PSX', ts: r.ts, price: r.price, volume: r.volume, value: null, raw: r }));
      // save in batches to avoid blocking
      const BATCH = 800;
      for (let i = 0; i < items.length; i += BATCH) {
        const chunk = items.slice(i, i + BATCH);
        await storage.saveSnapshots(chunk);
      }
      const finalCount = await storage.countSnapshots();
      setSnapshotCount(finalCount);
      setLoading(false);
      return { imported: true, count: finalCount };
    } catch (err) {
      setLoading(false);
      setError(err.message || String(err));
      return { imported: false, error: err.message };
    }
  }, []);

  const refreshForInterval = useCallback(async (interval = 'Day') => {
    setLoading(true);
    setError(null);
    try {
      // ensure db has snapshots
      await importSnapshotsIfNeeded();
      // gather timestamps
      const tsList = await storage.getAllTimestamps();
      setSnapshotCount(await storage.countSnapshots());
      setLatestTimestamp(tsList && tsList.length ? tsList[tsList.length - 1] : null);
      if (!tsList || tsList.length === 0) {
        setCoins([]);
        setLoading(false);
        return;
      }
      const latestTs = tsList[tsList.length - 1];
      // latest index
      const latestIdx = tsList.length - 1;
      const lookback = INTERVAL_LOOKUP[interval] || 1;
      const targetIdx = Math.max(0, latestIdx - lookback);
      const earlierTs = tsList[targetIdx];

      // get latest snapshots (one per symbol)
      const latest = await storage.getLatestAll();
      // build coins
      const out = [];
      for (const row of latest) {
        const sym = row.symbol;
        const later = row; // latest entry for symbol
        const prev = await storage.getSnapshotAtOrBefore(sym, earlierTs);
        let intervalPct = null;
        if (prev && prev.price != null && prev.price !== 0 && later.price != null) {
          intervalPct = ((later.price - prev.price) / prev.price) * 100;
        }
        // determine daily percent from raw if present
        const dailyRaw = later && later.raw && (later.raw['Price Change % 1 day'] || later.raw['Price Change % 1 Day'] || later.raw['Price Change %'] || later.raw.daily_pct);
        const dailyPct = dailyRaw != null ? Number(dailyRaw) : null;

        out.push({
          id: sym,
          symbol: sym,
          name: (later.raw && (later.raw.Description || later.raw.description)) || sym,
          price: later.price,
          volume: later.volume,
          // price_change_percentage_24h will represent the selected-interval percent (for display/color)
          price_change_percentage_24h: intervalPct,
          // keep daily change separate so bubble sizing can use it
          daily_change_1d: dailyPct,
          raw: later.raw,
          ts: later.ts
        });
      }
      setCoins(out.sort((a, b) => (b.daily_change_1d || 0) - (a.daily_change_1d || 0)));
      setLoading(false);
      return out;
    } catch (err) {
      setLoading(false);
      setError(err.message || String(err));
      return [];
    }
  }, [importSnapshotsIfNeeded]);

  useEffect(() => {
    // on mount try to ensure snapshots exist and compute Day by default
    (async () => {
      await importSnapshotsIfNeeded();
      await refreshForInterval('Day');
    })();
  }, [importSnapshotsIfNeeded, refreshForInterval]);

  return { coins, loading, error, importSnapshotsIfNeeded, refreshForInterval };
}
