import { useEffect, useState, useCallback } from 'react';
import storage from '../lib/storage';
import { ENABLE_REPO_SNAPSHOTS, ENABLE_LIVE_API, LIVE_API_BASE_URL, LIVE_API_KEY } from '../config';

// mapping of friendly interval -> trading-day count
const INTERVAL_LOOKUP = {
  'Day': 1,
  'Week': 5,
  'Month': 22,
  'Year': 252
};

const LIVE_INTERVAL_MAP = {
  '1 Min': '1m',
  '5 Min': '5m',
  '15 Min': '15m',
  'Hour': '1h',
  'Day': 'Day',
  'Week': 'Day',
  'Month': 'Day',
  'Year': 'Day'
};

const fallbackName = (symbol) => (symbol || '').toUpperCase();

async function fetchLiveInterval(interval) {
  const apiInterval = LIVE_INTERVAL_MAP[interval] || LIVE_INTERVAL_MAP.Day;
  const origin = typeof window !== 'undefined' ? window.location.origin : '';
  const base = LIVE_API_BASE_URL.startsWith('http')
    ? LIVE_API_BASE_URL
    : `${origin}${LIVE_API_BASE_URL.startsWith('/') ? '' : '/'}${LIVE_API_BASE_URL}`;
  const url = new URL('bubbles', base.endsWith('/') ? base : `${base}/`);
  url.searchParams.set('interval', apiInterval);
  const headers = {
    'Content-Type': 'application/json',
    'Cache-Control': 'no-cache',
    'Pragma': 'no-cache'
  };
  if (LIVE_API_KEY) headers['x-api-key'] = LIVE_API_KEY;

  const MAX_RETRIES = 3;
  let attempt = 0;

  while (attempt <= MAX_RETRIES) {
    try {
      // Add timestamp to URL to bypass browser cache
      url.searchParams.set('_t', Date.now().toString());
      const res = await fetch(url.toString(), {
        headers,
        cache: 'no-store'
      });

      if (res.status === 429) {
        attempt++;
        if (attempt > MAX_RETRIES) throw new Error(`Live API rate limit exceeded (${res.status})`);
        // Exponential backoff: 1s, 2s, 4s
        const delay = Math.pow(2, attempt - 1) * 1000;
        console.warn(`[useOHLCV] Rate limit hit, retrying in ${delay}ms...`);
        await new Promise(resolve => setTimeout(resolve, delay));
        continue;
      }

      if (!res.ok) {
        throw new Error(`Live API error (${res.status})`);
      }

      const json = await res.json();
      if (!json || !Array.isArray(json.symbols)) {
        return [];
      }
      return json.symbols.map((row) => ({
        id: row.symbol,
        symbol: row.symbol,
        name: row.name || fallbackName(row.symbol),
        price: Number(row.price ?? 0),
        volume: row.volume != null ? Number(row.volume) : null,
        price_change_percentage_24h: Number(row.intervalPct ?? 0),
        daily_change_1d: row.dailyPct != null ? Number(row.dailyPct) : null,
        ts: row.ts ? Number(new Date(row.ts).getTime()) : null,
        raw: row
      }));
    } catch (err) {
      if (attempt >= MAX_RETRIES) throw err;
      attempt++;
      // Simple retry for network errors
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }
  return [];
}

export default function useOHLCV() {
  const [coins, setCoins] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [snapshotCount, setSnapshotCount] = useState(0);
  const [latestTimestamp, setLatestTimestamp] = useState(null);

  const importSnapshotsIfNeeded = useCallback(async (force = false) => {
    try {
      if (ENABLE_LIVE_API) {
        setSnapshotCount(null);
        return { imported: false, count: null };
      }

      const cnt = await storage.countSnapshots();
      // If repository-driven snapshots are disabled, do not auto-import from
      // public/psx_snapshots.json. Respect manual CSV uploads only.
      if (!ENABLE_REPO_SNAPSHOTS) {
        setSnapshotCount(cnt);
        return { imported: false, count: cnt };
      }
      if (!force && cnt && cnt > 0) {
        setSnapshotCount(cnt);
        return { imported: false, count: cnt };
      }
      setLoading(true);
      if (force && cnt && cnt > 0) {
        // clear DB to force a fresh import
        await storage.clearSnapshots();
      }
      // fetch prebuilt JSON (generated by scripts/generate_snapshots_json.cjs -> public/psx_snapshots.json)
      const res = await fetch('/psx_snapshots.json');
      if (!res.ok) throw new Error('Failed to fetch snapshots JSON');
      const list = await res.json();
      // If JSON is very large it likely contains full history; to avoid importing huge amounts
      // (and duplicate entries) collapse to latest-per-symbol when the file is enormous.
      let filteredList = list;
      if (Array.isArray(list) && list.length > 100000) {
        // keep only the latest timestamp record per symbol
        const latestBySymbol = new Map();
        for (const r of list) {
          const sym = r.symbol;
          const cur = latestBySymbol.get(sym);
          if (!cur || (r.ts || 0) > (cur.ts || 0)) latestBySymbol.set(sym, r);
        }
        filteredList = Array.from(latestBySymbol.values());
        console.info('[useOHLCV] large snapshots JSON detected; importing latest-per-symbol only', filteredList.length);
      } else {
        // remove exact duplicates (same symbol + ts) if any
        const seen = new Set();
        filteredList = list.filter((r) => {
          const k = `${r.symbol}|${r.ts}`;
          if (seen.has(k)) return false;
          seen.add(k);
          return true;
        });
        if (filteredList.length !== list.length) console.info('[useOHLCV] removed duplicate snapshot records', list.length - filteredList.length);
      }
      // convert to storage format
      const items = filteredList.map((r) => ({ symbol: r.symbol, market: r.market || 'PSX', ts: r.ts, price: r.price, volume: r.volume, value: null, raw: r }));
      // save in batches to avoid blocking
      const BATCH = 800;
      for (let i = 0; i < items.length; i += BATCH) {
        const chunk = items.slice(i, i + BATCH);
        await storage.saveSnapshots(chunk);
      }
      const finalCount = await storage.countSnapshots();
      setSnapshotCount(finalCount);
      setLoading(false);
      return { imported: true, count: finalCount };
    } catch (err) {
      setLoading(false);
      setError(err.message || String(err));
      return { imported: false, error: err.message };
    }
  }, []);

  const refreshForInterval = useCallback(async (interval = 'Day') => {
    setLoading(true);
    setError(null);
    try {
      if (ENABLE_LIVE_API) {
        const liveCoins = await fetchLiveInterval(interval);
        setCoins(liveCoins);
        setSnapshotCount(liveCoins.length);
        setLatestTimestamp(liveCoins.reduce((latest, row) => (row.ts && row.ts > latest ? row.ts : latest), null));
        setLoading(false);
        return liveCoins;
      }

      // ensure db has snapshots
      await importSnapshotsIfNeeded();
      // gather timestamps
      const tsList = await storage.getAllTimestamps();
      setSnapshotCount(await storage.countSnapshots());
      setLatestTimestamp(tsList && tsList.length ? tsList[tsList.length - 1] : null);
      if (!tsList || tsList.length === 0) {
        setCoins([]);
        setLoading(false);
        return;
      }
      const latestTs = tsList[tsList.length - 1];
      // latest index
      const latestIdx = tsList.length - 1;
      const lookback = INTERVAL_LOOKUP[interval] || 1;
      const targetIdx = Math.max(0, latestIdx - lookback);
      const earlierTs = tsList[targetIdx];

      // get latest snapshots (one per symbol)
      const latest = await storage.getLatestAll();
      // build coins
      const out = [];
      for (const row of latest) {
        const sym = row.symbol;
        const later = row; // latest entry for symbol
        const prev = await storage.getSnapshotAtOrBefore(sym, earlierTs);
        let intervalPct = null;
        if (prev && prev.price != null && prev.price !== 0 && later.price != null) {
          intervalPct = ((later.price - prev.price) / prev.price) * 100;
        }
        // determine daily percent from raw if present
        const dailyRaw = later && later.raw && (later.raw['Price Change % 1 day'] || later.raw['Price Change % 1 Day'] || later.raw['Price Change %'] || later.raw.daily_pct);
        const dailyPct = dailyRaw != null ? Number(dailyRaw) : null;

        out.push({
          id: sym,
          symbol: sym,
          name: (later.raw && (later.raw.Description || later.raw.description)) || sym,
          price: later.price,
          volume: later.volume,
          // price_change_percentage_24h will represent the selected-interval percent (for display/color)
          price_change_percentage_24h: intervalPct,
          // keep daily change separate so bubble sizing can use it
          daily_change_1d: dailyPct,
          raw: later.raw,
          ts: later.ts
        });
      }
      setCoins(out.sort((a, b) => Math.abs(b.price_change_percentage_24h || 0) - Math.abs(a.price_change_percentage_24h || 0)));
      setLoading(false);
      return out;
    } catch (err) {
      setLoading(false);
      setError(err.message || String(err));
      return [];
    }
  }, [importSnapshotsIfNeeded]);

  useEffect(() => {
    (async () => {
      if (!ENABLE_LIVE_API) {
        await importSnapshotsIfNeeded();
      }
      await refreshForInterval('Day');
    })();
  }, [importSnapshotsIfNeeded, refreshForInterval]);

  return {
    coins,
    loading,
    error,
    importSnapshotsIfNeeded,
    refreshForInterval,
    snapCount: snapshotCount,
    latestTimestamp
  };
}
