apiVersion: 1

datasources:
  - name: questdb
    type: postgres
    uid: questdb
    access: proxy
    url: questdb:8812
    user: admin
    database: main
    jsonData:
      sslmode: "disable"
      postgresVersion: 1200
      timescaledb: false
    secureJsonData:
      password: quest
    isDefault: true
